[package]
name = "sg-rs"
version = "0.1.0"
authors = ["AnthonyMl <mladenov.anthony@gmail.com>"]

[dependencies]
glium = "0.14.0"
crossbeam = "0.2.9"
time = "0.1"
cgmath = "0.9.1"
tobj = "0.1.1"
mioco = "*"
